In [1]:
from __future__ import print_function
import torch

不初始化的$5\times3$矩阵

In [4]:
x = torch.empty(5,3)
print(x)

tensor([[4.5267e+21, 1.8672e+25, 1.1724e-19],
        [1.3563e-19, 1.3563e-19, 5.0746e+31],
        [1.2708e+31, 1.9433e-19, 2.7904e+29],
        [1.7836e+31, 6.8608e+22, 2.9514e+29],
        [5.5355e-11, 1.3556e-19, 1.5993e+34]])


随机初始化

In [5]:
x = torch.rand(5,3)
print(x)

tensor([[0.0747, 0.5751, 0.0965],
        [0.1460, 0.9032, 0.2633],
        [0.3092, 0.4380, 0.3999],
        [0.4203, 0.6113, 0.6773],
        [0.9273, 0.6047, 0.3680]])


全为0且类型为long

In [7]:
x = torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


直接使用数据

In [9]:
x = torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


基于已经存在的tensor

In [10]:
x = x.new_ones(5, 3, dtype=torch.double)      
# new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    
# override dtype!
print(x)                                      
# result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.5670,  0.3203, -0.3362],
        [-0.2615, -0.7482, -0.9720],
        [ 1.6276, -0.0099, -0.2872],
        [ 0.3641, -0.8966, -0.3726],
        [-1.2237,  1.0545,  0.1486]])


获取维度

In [12]:
print(x.size())

torch.Size([5, 3])


加法

In [13]:
y = torch.rand(5,3)
print(x+y)

tensor([[ 0.5795,  0.8353, -0.0735],
        [ 0.5668, -0.2014, -0.8395],
        [ 1.7979,  0.5391,  0.2801],
        [ 0.7317, -0.2385,  0.2413],
        [-0.3226,  1.0807,  0.7944]])


In [14]:
print(torch.add(x,y))

tensor([[ 0.5795,  0.8353, -0.0735],
        [ 0.5668, -0.2014, -0.8395],
        [ 1.7979,  0.5391,  0.2801],
        [ 0.7317, -0.2385,  0.2413],
        [-0.3226,  1.0807,  0.7944]])


In [15]:
res = torch.empty(5,3)
torch.add(x,y,out=res)
print(res)

tensor([[ 0.5795,  0.8353, -0.0735],
        [ 0.5668, -0.2014, -0.8395],
        [ 1.7979,  0.5391,  0.2801],
        [ 0.7317, -0.2385,  0.2413],
        [-0.3226,  1.0807,  0.7944]])


In [16]:
y.add_(x)
print(y)

tensor([[ 0.5795,  0.8353, -0.0735],
        [ 0.5668, -0.2014, -0.8395],
        [ 1.7979,  0.5391,  0.2801],
        [ 0.7317, -0.2385,  0.2413],
        [-0.3226,  1.0807,  0.7944]])


索引

In [17]:
print(x[:,1])

tensor([ 0.3203, -0.7482, -0.0099, -0.8966,  1.0545])


改变大小

In [18]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8)
print(x.size(),y.size(),z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


获得value

In [19]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.9753])
0.9752683639526367
