In [1]:
import torch

使用`requires_grad=True`跟踪运算

In [2]:
x = torch.ones(2,2,requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [3]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [4]:
print(y.grad_fn)

作为操作的结果被创建,y和z拥有grad_fn

In [5]:
z = y*y*3
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


`.requires_grad_()`会改变requires_grad属性，默认为False

In [7]:
a = torch.randn(2,2)
a = ((a*3) / (a-1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)

b = (a*a).sum()
print(b.grad_fn)

False
True


`out.backward()`等同`out.backward(torch.tensor(1.))`，进行后向传播

In [8]:
out.backward()

打印梯度$\frac{dout}{dx}$

In [9]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


雅可比向量积的例子

In [11]:
x = torch.randn(3,requires_grad=True)
y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([1399.9203, -533.7499, -715.3821], grad_fn=<MulBackward0>)


这种情况下，y不再是标量，autograd不能直接计算整个雅可比。但是如果我们只想要雅可比向量积，只需要简单传递向量给backward作为参数

In [12]:
v = torch.tensor([.1,1.,.0001], dtype=torch.float)
y.backward(v)
print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


可以通过包裹`with torch.no_grad()`通知跟踪autograd

In [14]:
print(x.requires_grad)
print((x**2).requires_grad)

with torch.no_grad():
    print((x**2).requires_grad)

True
True
False
